version: '2'

services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        container_name: tg-proxy
        ports:
          - "8239:443" #Proxy port, if you wish to change port - change left side 443 to another. Right side - it is port inside docker container
          - "8340:443"
          - "8341:443"
          - "8342:443"
          - "8343:443"
          - "8344:443"
          - "8345:443"
          - "8346:443"
          - "8347:443"
          - "8348:443"
          - "8349:443"
          - "8350:443"
          - "8351:443"
          - "8352:443"
          - "8353:443"
          - "8354:443"
          - "8355:443"
          - "8356:443"
          - "8357:443"
          - "8358:443"
          - "8359:443"
          - "8360:443"
          - "8361:443"
          - "8362:443"
          - "8363:443"
          - "8364:443"
          - "8365:443"
          - "8366:443"
          - "8367:443"
          - "8368:443"
          - "8369:443"
          - "8370:443"
          - "8371:443"
          - "8372:443"
          - "8373:443"
          - "8374:443"
          - "8375:443"
          - "8376:443"
          - "8377:443"
          - "8378:443"
          - "8379:443"
          - "8380:443" 
          - "8381:443"
          - "8382:443"
          - "8383:443"
          - "8384:443"
          - "8385:443"
          - "8386:443"
          - "8387:443"
          - "8388:443"
          - "8389:443"
          - "8390:443"
          - "8391:443"
          - "8392:443"
          - "8393:443"
          - "8394:443"
          - "8395:443"
          - "8396:443"
          - "8397:443"
          - "8398:443"
          - "8399:443"
          - "8410:443"
          - "8411:443"
          - "8412:443"
          - "8413:443"
          - "8414:443"
          - "8415:443"
          - "8416:443"
          - "8417:443"
          - "8418:443"
          - "8419:443"
          - "8420:443"
          - "8421:443"
          - "8422:443"
          - "8423:443"
          - "8424:443"
          - "8425:443"
          - "8426:443"
          - "8427:443"
          - "8428:443"
          - "8429:443"
          - "8430:443"
        volumes:
           - "proxy-config:/data"
        restart: unless-stopped
        env_file:
           - ./config.env
    tg-proxy-watchtower:
        image: v2tec/watchtower
        container_name: tg-proxy-watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /root/.docker/config.json:/config.json
        command: telegrammessenger/proxy:latest
        restart: unless-stopped
volumes:
  proxy-config:
